AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  APIHIVESNAMEHIST:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::035974012754:role/service-role/DoEverything'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /API_HIVES_NAME_HIST
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-east-1:336392948345:layer:AWSDataWrangler-Python39:5'
